<a href="https://colab.research.google.com/github/JasmanjotSarna/AI-ML-Learning/blob/main/Machine%20Learning/Insurance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import (
    r2_score,
    mean_absolute_error,
    mean_squared_error
)

In [ ]:
df=pd.read_csv('insurance.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [ ]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [ ]:
df_model=df.copy()

In [ ]:
df_model['sex']=df_model['sex'].str.strip()
df_model['smoker']=df_model['smoker'].str.strip()
df_model['region']=df_model['region'].str.strip()

In [ ]:
df_model=df_model.drop_duplicates()

In [ ]:
X = df_model.drop(columns='charges')
Y=df_model['charges']

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [ ]:
scaler= StandardScaler()

In [ ]:
X_train.head()

      age     sex     bmi  children smoker     region
1114   23    male  24.510         0     no  northeast
968    21    male  25.745         2     no  northeast
599    52  female  37.525         2     no  northwest
170    63    male  41.470         0     no  southeast
275    47  female  26.600         2     no  northeast

In [ ]:
# Age groups
X_train['age_group'] = pd.cut(
    X_train['age'],
    bins=[0, 18, 40, 60, float('inf')],
    labels=['Children', 'Young', 'Middle-aged', 'Senior']
)

X_test['age_group'] = pd.cut(
    X_test['age'],
    bins=[0, 18, 40, 60, float('inf')],
    labels=['Children', 'Young', 'Middle-aged', 'Senior']
)

# BMI categories
X_train['bmi_category'] = pd.cut(
    X_train['bmi'],
    bins=[0, 18.5, 25, 30, float('inf')],
    labels=['Underweight', 'Normal', 'Overweight', 'Obese']
)

X_test['bmi_category'] = pd.cut(
    X_test['bmi'],
    bins=[0, 18.5, 25, 30, float('inf')],
    labels=['Underweight', 'Normal', 'Overweight', 'Obese']
)

In [ ]:
X_train=pd.get_dummies(X_train,columns=['sex','region','smoker'],drop_first=True)
X_test=pd.get_dummies(X_test,columns=['sex','region','smoker'],drop_first=True)

In [ ]:
X_train.columns

Index(['age', 'bmi', 'children', 'age_group', 'bmi_category', 'sex_male',
       'region_northwest', 'region_southeast', 'region_southwest',
       'smoker_yes'],
      dtype='object')

In [ ]:
X_train.head()

,age,bmi,children,age_group,bmi_category,sex_male,region_northwest,region_southeast,region_southwest,smoker_yes
1114,23,24.510,0,Young,Normal,True,False,False,False,False
968,21,25.745,2,Young,Overweight,True,False,False,False,False
599,52,37.525,2,Middle-aged,Obese,False,True,False,False,False
170,63,41.470,0,Senior,Obese,True,False,True,False,False
275,47,26.600,2,Middle-aged,Overweight,False,False,False,False,False

In [ ]:
X_train= pd.get_dummies(X_train, columns = ['bmi_category'])
X_test= pd.get_dummies(X_test, columns = ['bmi_category'])

In [ ]:
X_train.head()

,age,bmi,children,age_group,sex_male,region_northwest,region_southeast,region_southwest,smoker_yes,bmi_category_Underweight,bmi_category_Normal,bmi_category_Overweight,bmi_category_Obese
1114,23,24.510,0,Young,True,False,False,False,False,False,True,False,False
968,21,25.745,2,Young,True,False,False,False,False,False,False,True,False
599,52,37.525,2,Middle-aged,False,True,False,False,False,False,False,False,True
170,63,41.470,0,Senior,True,False,True,False,False,False,False,False,True
275,47,26.600,2,Middle-aged,False,False,False,False,False,False,False,True,False

In [ ]:
X_train= pd.get_dummies(X_train, columns = ['age_group'])
X_test= pd.get_dummies(X_test, columns = ['age_group'])

In [ ]:

X_train.head()

,age,bmi,children,sex_male,region_northwest,region_southeast,region_southwest,smoker_yes,bmi_category_Underweight,bmi_category_Normal,bmi_category_Overweight,bmi_category_Obese,age_group_Children,age_group_Young,age_group_Middle-aged,age_group_Senior
1114,23,24.510,0,True,False,False,False,False,False,True,False,False,False,True,False,False
968,21,25.745,2,True,False,False,False,False,False,False,True,False,False,True,False,False
599,52,37.525,2,False,True,False,False,False,False,False,False,True,False,False,True,False
170,63,41.470,0,True,False,True,False,False,False,False,False,True,False,False,False,True
275,47,26.600,2,False,False,False,False,False,False,False,True,False,False,False,True,False

In [ ]:
cols= ['age','bmi','children']


X_train[cols]= scaler.fit_transform(X_train[cols])

In [ ]:
X_test[cols] = scaler.transform(X_test[cols])

In [ ]:
X_train.head()

,age,bmi,children,sex_male,region_northwest,region_southeast,region_southwest,smoker_yes,bmi_category_Underweight,bmi_category_Normal,bmi_category_Overweight,bmi_category_Obese,age_group_Children,age_group_Young,age_group_Middle-aged,age_group_Senior
1114,-1.157680,-0.996928,-0.907908,True,False,False,False,False,False,True,False,False,False,True,False,False
968,-1.300619,-0.792762,0.766904,True,False,False,False,False,False,False,True,False,False,True,False,False
599,0.914926,1.154664,0.766904,False,True,False,False,False,False,False,False,True,False,False,True,False
170,1.701087,1.806837,-0.907908,True,False,True,False,False,False,False,False,True,False,False,False,True
275,0.557580,-0.651417,0.766904,False,False,False,False,False,False,False,True,False,False,False,True,False

In [ ]:
X_test.head()

,age,bmi,children,sex_male,region_northwest,region_southeast,region_southwest,smoker_yes,bmi_category_Underweight,bmi_category_Normal,bmi_category_Overweight,bmi_category_Obese,age_group_Children,age_group_Young,age_group_Middle-aged,age_group_Senior
900,0.700518,-1.326734,-0.907908,True,False,False,False,False,False,True,False,False,False,False,True,False
1064,-0.728865,-0.816733,2.441716,False,False,False,True,False,False,False,True,False,False,True,False,False
1256,0.843457,0.966203,1.604310,False,True,False,False,False,False,False,False,True,False,False,True,False
298,-0.585927,0.636397,1.604310,True,True,False,False,True,False,False,False,True,False,True,False,False
237,-0.585927,1.297663,0.766904,True,False,True,False,False,False,False,False,True,False,True,False,False

In [ ]:
from scipy.stats import pearsonr

In [ ]:
X_train.columns

Index(['age', 'bmi', 'children', 'sex_male', 'region_northwest',
       'region_southeast', 'region_southwest', 'smoker_yes',
       'bmi_category_Underweight', 'bmi_category_Normal',
       'bmi_category_Overweight', 'bmi_category_Obese', 'age_group_Children',
       'age_group_Young', 'age_group_Middle-aged', 'age_group_Senior'],
      dtype='object')

In [ ]:
from scipy.stats import pearsonr
import pandas as pd

selected_features = [
    'age', 'bmi', 'children', 'sex_male',
    'region_northwest', 'region_southeast',
    'region_southwest', 'smoker_yes',
    'bmi_category_Underweight', 'bmi_category_Normal',
    'bmi_category_Overweight', 'bmi_category_Obese',
    'age_group_Children', 'age_group_Young',
    'age_group_Middle-aged', 'age_group_Senior'
]

correlations = {
    feature: pearsonr(X_train[feature], Y_train)[0]
    for feature in selected_features
}

correlation_df = pd.DataFrame(
    list(correlations.items()),
    columns=['Feature', 'Pearson Correlation']
)

correlation_df = correlation_df.sort_values(
    by='Pearson Correlation',
    ascending=False
)

correlation_df

                     Feature  Pearson Correlation
7                 smoker_yes             0.774131
0                        age             0.289691
11        bmi_category_Obese             0.193465
14     age_group_Middle-aged             0.183635
1                        bmi             0.178440
15          age_group_Senior             0.170884
2                   children             0.086172
5           region_southeast             0.078927
3                   sex_male             0.060167
6           region_southwest            -0.036003
4           region_northwest            -0.054955
8   bmi_category_Underweight            -0.063836
9        bmi_category_Normal            -0.093206
12        age_group_Children            -0.105411
10   bmi_category_Overweight            -0.117887
13           age_group_Young            -0.220223

In [ ]:
from scipy.stats import pearsonr
import pandas as pd

selected_features = [
    'age', 'bmi', 'children', 'sex_male',
    'region_northwest', 'region_southeast',
    'region_southwest', 'smoker_yes',
    'bmi_category_Underweight', 'bmi_category_Normal',
    'bmi_category_Overweight', 'bmi_category_Obese',
    'age_group_Children', 'age_group_Young',
    'age_group_Middle-aged', 'age_group_Senior'
]

correlations = {
    feature: pearsonr(X_test[feature], Y_test)[0]
    for feature in selected_features
}

correlation_df = pd.DataFrame(
    list(correlations.items()),
    columns=['Feature', 'Pearson Correlation']
)

correlation_df = correlation_df.sort_values(
    by='Pearson Correlation',
    ascending=False
)

correlation_df

                     Feature  Pearson Correlation
7                 smoker_yes             0.833592
0                        age             0.329962
1                        bmi             0.259945
11        bmi_category_Obese             0.220321
15          age_group_Senior             0.182159
14     age_group_Middle-aged             0.163239
3                   sex_male             0.058694
5           region_southeast             0.053261
4           region_northwest             0.022593
2                   children             0.002645
8   bmi_category_Underweight            -0.009965
6           region_southwest            -0.067432
10   bmi_category_Overweight            -0.123833
9        bmi_category_Normal            -0.149939
12        age_group_Children            -0.166689
13           age_group_Young            -0.176969

In [ ]:
cat_features = [
    'age', 'bmi', 'children', 'sex_male',
    'region_northwest', 'region_southeast',
    'region_southwest', 'smoker_yes',
    'bmi_category_Underweight', 'bmi_category_Normal',
    'bmi_category_Overweight', 'bmi_category_Obese',
    'age_group_Children', 'age_group_Young',
    'age_group_Middle-aged', 'age_group_Senior'
]

In [ ]:
cat_features = [col.strip() for col in cat_features]

In [ ]:
from scipy.stats import chi2_contingency
import pandas as pd

alpha = 0.05

# Bin training target
charges_bin_train = pd.qcut(
    Y_train, q=4, labels=False
)

chi2_results_train = {}

for col in cat_features:
    contingency = pd.crosstab(
        X_train[col], charges_bin_train
    )

    chi2_stat, p_val, _, _ = chi2_contingency(contingency)

    decision = (
        'Reject Null (Keep Feature)'
        if p_val < alpha
        else 'Fail to Reject Null'
    )

    chi2_results_train[col] = {
        'chi2_statistic': chi2_stat,
        'p_value': p_val,
        'Decision': decision
    }

chi2_df_train = pd.DataFrame(chi2_results_train).T
chi2_df_train = chi2_df_train.sort_values(by='p_value')

chi2_df_train

                         chi2_statistic   p_value                    Decision
age                         1228.698799       0.0  Reject Null (Keep Feature)
smoker_yes                    655.47917       0.0  Reject Null (Keep Feature)
age_group_Young              333.171095       0.0  Reject Null (Keep Feature)
age_group_Middle-aged        297.384585       0.0  Reject Null (Keep Feature)
age_group_Senior              98.210249       0.0  Reject Null (Keep Feature)
children                     118.482518       0.0  Reject Null (Keep Feature)
age_group_Children             64.86889       0.0  Reject Null (Keep Feature)
region_southeast              18.637539  0.000325  Reject Null (Keep Feature)
sex_male                       9.479228  0.023553  Reject Null (Keep Feature)
bmi_category_Obese             6.709749  0.081748         Fail to Reject Null
bmi_category_Underweight       5.040654  0.168844         Fail to Reject Null
bmi                         1536.195141  0.218598         Fail to Reject Null
region_southwest               4.036119   0.25759         Fail to Reject Null
bmi_category_Overweight        4.028395  0.258414         Fail to Reject Null
bmi_category_Normal            3.111256  0.374788         Fail to Reject Null
region_northwest               1.732898  0.629645         Fail to Reject Null

In [ ]:
selected_features = [
    'age',
    'sex_male',
    'bmi',
    'children',
    'smoker_yes',
    'age_group_Young',
    'age_group_Middle-aged',
    'age_group_Senior',
    'age_group_Children',
    'region_southeast'
]
X_train = X_train[selected_features]
X_test = X_test[selected_features]

In [ ]:
model = LinearRegression()

In [ ]:
model.fit(X_train,Y_train)

LinearRegression()

In [ ]:
y_pred=model.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score

r2 = r2_score(Y_test,y_pred)
r2
n = X_test.shape[0]
p = X_test.shape[1]
adjusted_r2 = 1 - ((1- r2) * (n-1) / (n - p - 1))
adjusted_r2

0.7945390727099532

In [ ]:
r2

0.8022342385260598

In [ ]:
mae = mean_absolute_error(Y_test, y_pred)
mae

4238.77624684449

In [ ]:
rmse = np.sqrt(mean_squared_error(Y_test, y_pred))
rmse

np.float64(6028.32131945056)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [ ]:
from sklearn.neighbors import KNeighborsRegressor

In [ ]:
knn_model = KNeighborsRegressor(n_neighbors =3)

In [ ]:
knn_model.fit(X_train,Y_train)

KNeighborsRegressor(n_neighbors=3)

In [ ]:
y_pred_knn = knn_model.predict(X_test)

In [ ]:
mae = mean_absolute_error(Y_test, y_pred_knn)
mse = mean_squared_error(Y_test, y_pred_knn)
rmse = np.sqrt(mse)
r2 = r2_score(Y_test, y_pred_knn)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE: 3785.2469116330853
MSE: 49325502.95166766
RMSE: 7023.21172624517
R2 Score: 0.7315707472889963

In [ ]:
adjusted_r2 = 1 - ((1- r2) * (n-1) / (n - p - 1))
adjusted_r2

0.7211260292846771